import type { BookData } from "./types"

export const booksData: BookData[] = [
  {
    id: "standards-specification",
    title: "规范标准",
    subtitle: "Standards and Specifications",
    author: "国家卫生健康委员会",
    publishedYear: 2024,
    pages: 428,
    description: [
      "定位：奠定系统的专业基准，确保建设与问答遵循统一的行业和法律标准。",
      "代表性内容：《综合医院建筑设计规范》GB 51039-2014｜住建部｜2015 实施 —— 功能分区、洁污流线、强制性条款；FGI《2022 医院设计与建造指南》｜美国｜2022 —— 新增重症烧伤 ICU、行为健康危机单元；《ASHRAE 170 通风标准》｜美国采暖制冷空调协会｜2021 —— 医疗建筑通风最低要求。价值说明：覆盖建筑、通风、感染防控、患者体验等核心标准，为医院设计与智慧化升级提供坚实依据。",
    ],
    genres: ["规范标准", "医疗信息化", "技术规范"],
    rating: 4.8,
    reviews: 2847,
    materialProps: {
      color: "#2563eb",
      metalness: 0.7,
      roughness: 0.3,
      emissive: "#1e40af",
      emissiveIntensity: 0.1,
      texture: {
        front: "/images/standard-front.png",
        back: "/images/standard-back.png",
      },
      offsetX: -0.01,
      offsetY: 0,
    },
    backgroundColor: "#1e40af",
    textColor: "white",
  },
  {
    id: "policy-documents",
    title: "政策文件",
    subtitle: "Policy Documents",
    author: "国家卫生健康委员会政策研究室",
    publishedYear: 2024,
    pages: 678,
    description: [
      "定位：提供国家战略导向与政策框架，是智能问答系统的政策依据。",
      "代表性内容：《关于推动公立医院高质量发展的意见》｜国务院办公厅｜2021；《公立医院高质量发展促进行动（2021—2025年）》｜国家卫健委｜2021；国新办/医保局权威解读：国家医学中心、区域医疗中心与智慧医院建设。价值说明：涵盖高质量发展、区域医疗中心、智慧医院三大政策导向，为医院数字化转型指明路径。",
    ],
    genres: ["政策文件", "医疗管理", "法规解读"],
    rating: 4.6,
    reviews: 1567,
    materialProps: {
      color: "#7c3aed",
      metalness: 0.5,
      roughness: 0.5,
      emissive: "#6d28d9",
      emissiveIntensity: 0.1,
      texture: {
        front: "/images/policy-front.png",
        back: "/images/policy-back.png",
      },
      offsetX: -0.02,
      offsetY: 0,
    },
    backgroundColor: "#6d28d9",
    textColor: "white",
  },
  {
    id: "books-reports",
    title: "书籍报告",
    subtitle: "Books and Reports",
    author: "中国医院协会信息专业委员会",
    publishedYear: 2024,
    pages: 356,
    description: [
      "定位：总结工程实践与研究趋势，兼顾设施韧性与未来智慧医院探索。",
      "代表性内容：FGI《2022 医院设计与建造指南（Hospitals）》｜2022；《The Pandemic Resilient Hospital》｜HKS｜2021 —— 疫情韧性与可转换空间；《Smart Hospitals》｜三井全球战略研究所｜2022 —— 数字孪生与分层架构试点。价值说明：涉及空间设计、应急韧性、智能化趋势，为战略决策与方案制定提供系统参考。",
    ],
    genres: ["书籍报告", "数字医疗", "行业分析"],
    rating: 4.7,
    reviews: 1923,
    materialProps: {
      color: "#059669",
      metalness: 0.6,
      roughness: 0.4,
      emissive: "#047857",
      emissiveIntensity: 0.1,
      texture: {
        front: "/images/book-front.png",
        back: "/images/book-back.png",
      },
      offsetX: -0.02,
      offsetY: 0,
    },
    backgroundColor: "#047857",
    textColor: "white",
  },
  {
    id: "research-papers",
    title: "参考论文",
    subtitle: "Research Papers",
    author: "清华大学医学院",
    publishedYear: 2024,
    pages: 512,
    description: [
      "定位：汇聚学术证据与前沿研究，确保回答具备科研支撑。",
      "代表性内容：系统综述｜2024 —— ICU 单人病房显著降低感染与耐药风险；系统综述｜BMJ Open｜2023 —— 单人病房在新生儿与重症人群临床获益；综述｜Frontiers in Built Environment｜2024 —— 亲生物设计缩短住院时长、降低死亡率；综述｜2023 —— 数字孪生优化流程、提升个性化照护。价值说明：论文覆盖感染控制、疗愈环境、数字孪生等主题，使系统具备循证性与前瞻性。",
    ],
    genres: ["参考论文", "人工智能", "医学研究"],
    rating: 4.9,
    reviews: 3456,
    materialProps: {
      color: "#dc2626",
      metalness: 0.8,
      roughness: 0.2,
      emissive: "#b91c1c",
      emissiveIntensity: 0.1,
      texture: {
        front: "/images/paper-front.png",
        back: "/images/paper-back.png",
      },
      offsetX: -0.01,
      offsetY: 0,
    },
    backgroundColor: "#b91c1c",
    textColor: "white",
  },
  {
    id: "online-cases",
    title: "在线案例",
    subtitle: "Online Cases",
    author: "中国医院协会",
    publishedYear: 2024,
    pages: 394,
    description: [
      "定位：呈现国内外医院的智慧化与设计实践，便于参考与落地。",
      "代表性内容：上海嘉会国际医院｜NBBJ —— 花园式院区，LEED Healthcare Gold 认证；厦门弘爱医院｜Lemanarc —— 模块化、标准化设计，强调快速建造与可持续运营；无锡医院｜NBBJ —— 融合水文化与康复体验的场景化疗愈设计；ArchDaily 医院专题页 —— 全球医院建筑精选案例。价值说明：案例突出人本体验、绿色节能、在地文化、智慧医疗应用，帮助用户从实践中获取启发。",
    ],
    genres: ["在线案例", "智慧医院", "实践经验"],
    rating: 4.8,
    reviews: 2134,
    materialProps: {
      color: "#ea580c",
      metalness: 0.6,
      roughness: 0.4,
      emissive: "#c2410c",
      emissiveIntensity: 0.1,
      texture: {
        front: "/images/onlinecases-front.png",
        back: "/images/onlinecases-back.png",
      },
      offsetX: -0.01,
      offsetY: 0,
    },
    backgroundColor: "#c2410c",
    textColor: "white",
  },
]
